#!/system/bin/sh
#
#written by steve lovejoy aka lovejoy777
#
#
echo 'boot-recovery' > /cache/recovery/command
echo '--update_package=/data/data/com.sion.lovejoy777sa.sion/otaroms/otarom.zip' >> /cache/recovery/command
reboot recovery
